# -------------------------------------------
# Kubernetes Scheduler + Affinity + Resources
# -------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-affinity-resources
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity-resources
  template:
    metadata:
      labels:
        app: affinity-resources
    spec:
      containers:
        - name: nginx
          image: nginx
          # Escala de verificación 3
          resources:
            requests:
              cpu: "700m"
              memory: "700Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

      # escala 2 de verificación: nodo 2
      tolerations:
        - key: gpu # Clave del taint del nodo
          operator: Equal # Debe coincidir exactamente llave + valor
          value: ml # Valor esperado del taint
          effect: NoSchedule # Para poder programar en nodos con taint

      affinity:
        nodeAffinity:
          # escala 1 de verificación
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch # topology keys
                    operator: In
                    values:
                      - amd64 # Solo nodos con esta arquitectura

          # escala 4 de verificación
          preferredDuringSchedulingIgnoredDuringExecution:
            # Pesos
            - weight: 100
              preference:
                matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      - "true" # Prefiere nodos con GPU disponible

            - weight: 50
              preference:
                matchExpressions:
                  - key: fast-ssd
                    operator: Exists # Solo requiere que exista la etiqueta (key), el valor da lo mismo

            - weight: 20
              preference:
                matchExpressions:
                  - key: maintenance
                    operator: DoesNotExist # Prefiere nodos que no tengan esta etiqueta

