apiVersion: v1
kind: Pod
metadata:
  name: pod-no-token
  namespace: security-lab
spec:
  # deshabilitar montado de sa
  automountServiceAccountToken: false
  containers:
    - name: nginx
      image: nginx
